# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
es:
  languageCode: es-es
  contentDir: content/es
  menu:
    main:
    - name: Inicio
      url: '#about'
      weight: 10
    - name: Publicaciones
      url: '#publications'
      weight: 15
    - name: Docencia
      url: '#accomplishments'
      weight: 20
    - name: Comunicación
      url: '#experience'
      weight: 25
    - name: Prensa
      url: '#posts'
      weight: 30
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
